## Numpy

In [98]:
#importar a biblioteca numpy; pode-se usar um alias para facilitar
# se der erro, abrir o terminal e digitar pip install numpy
import numpy as np

In [9]:
#Criar um array
array = np.array([1, 2, 3, 5, 7])
print(array)

[1 2 3 5 7]


In [10]:
#para saber o tipo do array
print(type(array))

<class 'numpy.ndarray'>


In [11]:
#Criar um array com um tipo específico
#float de 64 bits
array_float = np.array([1, 2, 3, 4, 5], dtype = np.float64)
print(array_float)
print("Tipo: ", type(array_float))

[1. 2. 3. 4. 5.]
Tipo:  <class 'numpy.ndarray'>


In [12]:
#Criando um array de inteiros de 32 bits
array_int = np.array([1, 2, 3, 4, 5], dtype = np.int32)
print(array_int)
print("Tipo: ", type(array_int))

[1 2 3 4 5]
Tipo:  <class 'numpy.ndarray'>


### Alterando o tipo do array

In [13]:
array1 = np.array([1.2, 3.5, 7, 2.6666])
print(array1)

[1.2    3.5    7.     2.6666]


In [17]:
#convertendo os elementos de float para int
array1_int = array1.astype(np.int32)
print(array1_int)

[1 3 7 2]


In [18]:
#convertendo de int para float
array2 = np.array([2, 5, 8])
array2_float = array2.astype(np.float64)
print(array2_float)

[2. 5. 8.]


### Arrays multidimensionais

In [22]:
#Criando um array bidimensional (matriz)

matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [112]:
#Criando uma matriz 3 X 2 (3 linhas e 2 colunas) com valores zero
matriz_zero = np.zeros([3, 2]) #Os valores entre os colchetes se referem ao número de linhas e colunas
print(matriz_zero)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [27]:
#Criando uma matriz 4x5 com valores 1
matriz_um = np.ones([4, 5])
print(matriz_um)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [28]:
# É possível definir como inteiro
matriz_um_int = np.ones([4, 5], dtype = np.int32)
print(matriz_um_int)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [44]:
# Matriz identidade = Matriz quadrada em que a diagonal principal tenha valor 1 e os outros 0
matriz_identidade = np.eye(3) #nos parametros, só preciso definir o tamanho da matriz, já que é quadrada
# se quiser, pode definir o tipo da matriz, colocando dtype = np.int32 como segundo parametro
#matriz_identidade = np.eye(3, dtype = np.int32) 
print(matriz_identidade)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [45]:
# Para ver as dimensoes de uma matriz
print(matriz_identidade.shape)

(3, 3)


### Valores aleatórios

In [35]:
#Array com valores aleatórios entre 0 e 1
array_aleatorio = np.random.random(3)
print(array_aleatorio)

[0.96621476 0.73755282 0.07320545]


In [48]:
# Matriz com valores aleatórios entre 0 e 1
matriz_aleatoria = np.random.random([4, 2])
print(matriz_aleatoria)

[[0.95321654 0.61395753]
 [0.27879673 0.73336515]
 [0.55320777 0.08572439]
 [0.99416335 0.58443953]]


In [49]:
# Valores aleatórios inteiros
array_aleatorio_int = np.random.randint(4, size = (2, 5))
#gera um array 2x5 com numeros aleatorios entre 0 e 4 (0, 1, 2, 3)
print(array_aleatorio_int)

[[0 0 3 0 2]
 [1 0 1 3 3]]


### Funções Matemáticas

In [56]:
# criando uma matriz para os testes
matriz_teste = np.array([[1, 4, 5], [12, -3, 8]])
print(matriz_teste)

[[ 1  4  5]
 [12 -3  8]]


In [59]:
# Maior valor da matriz
print(matriz_teste.max())

12


In [60]:
# Menor valor da matriz
print(matriz_teste.min())

-3


In [61]:
# Soma dos elementos da matriz
print(matriz_teste.sum())

27


In [62]:
# Média dos valores da matriz
print(matriz_teste.mean())

4.5


In [63]:
# Raiz quadrada
matriz_teste2 = np.array([[4, 9, 25], [16, 36, 49], [64, 81, 121]])
print(np.sqrt(matriz_teste2))

[[ 2.  3.  5.]
 [ 4.  6.  7.]
 [ 8.  9. 11.]]


In [71]:
# Potências
array_teste = np.array([2, 4, 5])

#Quadrado dos elementos
print(np.power(array_teste, 2))

# Elementos elevados ao cubo
print(np.power(array_teste, 3))

[ 4 16 25]
[  8  64 125]


### Extração de elementos

In [72]:
array_teste = np.array([1, 3, 7, 4, 8, 9, 2, 6])

# Terceiro elemento do array
print(array_teste[2])

7


In [73]:
#dois primeiros elementos do array (intervalo de 0 a 2)
print(array_teste[0:2])

[1 3]


In [74]:
# Intervalo entre o segundo elemento e o 5o. elemento do array
print(array_teste[1:5])

[3 7 4 8]


In [75]:
# Elementos a partir da terceira posição, até o final
print(array_teste[2:])

[7 4 8 9 2 6]


In [76]:
# Elementos a partir da penultima posição
print(array_teste[-2:])

[2 6]


In [78]:
# Quatro últimos elementos do array
print(array_teste[-4:])

[8 9 2 6]


#### Extração de elementos da matriz

In [80]:
matriz_teste = np.array([[4, 2, 1], [5, 3, 7], [6, 8, 9]])

print(matriz_teste)

[[4 2 1]
 [5 3 7]
 [6 8 9]]


In [81]:
# Exibir a primeira linha
print(matriz_teste[0, :])

[4 2 1]


In [82]:
# Exibir a segunda coluna
print(matriz_teste[:, 1])

[2 3 8]


In [83]:
# Exibir os dois elementos da primeira e segunda linhas
print(matriz_teste[0:2, 0:2])

[[4 2]
 [5 3]]


### Operações entre matrizes

In [85]:
# Criação de duas matrizes
m1 = np.array([[2, 4, 3], [1, 5, 6]])
m2 = np.array([[1, 6, 2], [9, 0, 7]])
print(m1)
print(m2)

[[2 4 3]
 [1 5 6]]
[[1 6 2]
 [9 0 7]]


In [88]:
# Soma entre matrizes
# As duas matrizes devem ser do mesmo tamanho
# O resultado será uma matriz também do mesmo tamanho
print(m1 + m2)

[[ 3 10  5]
 [10  5 13]]


In [87]:
# Subtração: mesmas regras da soma
print(m1 - m2)

[[ 1 -2  1]
 [-8  5 -1]]


In [89]:
# Outra situação
m3 = np.array([[1, 2, 3]])
print(m1 + m3)

[[3 6 6]
 [2 7 9]]


In [109]:
# Multiplicação

print(m1 * m2)

# Neste caso, os elementos são simplesmente multiplicados um a um

[[ 2 24  6]
 [ 9  0 42]]


In [110]:
# Multiplicação entre matrizes - forma matemática
# A primeira matriz deve ter o número de colunas equivalente ao número de linhas da segunda matriz
# Ex: multiplicação de uma matriz 3x2 por uma matriz 2x4
m4 = np.array([[1, 2], [0, 1], [4, 3]])
print(m4)
print("-----------")
m5 = np.array([[0, 2, 3, 1], [1, 4, 3, 5]])
print(m5)

[[1 2]
 [0 1]
 [4 3]]
-----------
[[0 2 3 1]
 [1 4 3 5]]


In [111]:
# A matriz resultante vai ter tamanho equivalente a linhas(matriz1) x colunas(matriz2) = 3x4
# Para a operação matemática, deve-se usar np.dot()
print(np.dot(m4, m5))

[[ 2 10  9 11]
 [ 1  4  3  5]
 [ 3 20 21 19]]


### Where

In [115]:
# Criando uma matriz 3 x 3
matriz_3 = np.array([[0, 1, 3], [-2, 4, 5], [-1, 3, 7]])
print(matriz_3)

[[ 0  1  3]
 [-2  4  5]
 [-1  3  7]]


In [125]:
# Criar uma matriz de booleanos verificando se os números estão entre 1 e 3
matriz_bool = (matriz_3 >= 1)
print(matriz_bool)

[[False  True  True]
 [False  True  True]
 [False  True  True]]


In [126]:
# Criar uma matriz com valores 0, se os números forem menores que 3 e 1
matriz_nova = np.where(matriz_3 < 3, 0, 1) #where funciona como um operador ternário
print(matriz_nova)

[[0 0 1]
 [0 1 1]
 [0 1 1]]
